
import type { ReactNode } from 'react';
import { Character, ReactionType } from './types';

export const INITIAL_CHARACTERS: Character[] = [
  {
    id: 'kirito',
    name: 'Kirito',
    avatar: '⚔️',
    personality: 'A skilled gamer, often a lone wolf but deeply protective of his friends. Tends to be direct, serious, and a bit awkward in social situations. Often thinks about virtual worlds, skills, and swords. Speaks concisely.',
    interests: ['video games', 'virtual reality', 'swordsmanship', 'exploring dungeons', 'black outfits'],
    angerLevel: 0,
    isBanned: false,
    recentEvents: [],
  },
  {
    id: 'asuna',
    name: 'Asuna',
    avatar: '🍳',
    personality: 'A kind, caring, and strong-willed leader. She is an excellent cook and a formidable fighter who values friendship and love. She is responsible and sometimes acts as the mother of the group. Speaks warmly and politely.',
    interests: ['cooking', 'friendship', 'guild management', 'helping others', 'picnics'],
    angerLevel: 0,
    isBanned: false,
    recentEvents: [],
  },
  {
    id: 'ichikawa',
    name: 'Ichikawa',
    avatar: '📓',
    personality: 'An introverted middle schooler with a rich, dark fantasy inner world. He often overthinks social situations and assumes the worst. Deep down, he is kind and incredibly observant, especially towards Yamada. His posts are often cynical or muttered thoughts.',
    interests: ['reading', 'observing people', 'psychological thrillers', 'Yamada Anna'],
    angerLevel: 0,
    isBanned: false,
    recentEvents: [],
  },
  {
    id: 'yamada',
    name: 'Yamada',
    avatar: '🍬',
    personality: 'A cheerful, friendly, and slightly air-headed model who loves to snack. She is surprisingly down-to-earth and approachable, often oblivious to social cues but has a pure heart. She is very open and expressive with her feelings.',
    interests: ['snacking', 'sweets', 'manga', 'hanging out with friends', 'Ichikawa'],
    angerLevel: 0,
    isBanned: false,
    recentEvents: [],
  },
  {
    id: 'goku',
    name: 'Goku',
    avatar: '🐉',
    personality: 'Pure-hearted, cheerful, and endlessly optimistic. His main motivations are fighting strong opponents to test his limits and protecting his friends and family. He is simple-minded and has a voracious appetite. Gets excited easily.',
    interests: ['fighting', 'eating', 'training', 'making new friends', 'finding dragon balls'],
    angerLevel: 0,
    isBanned: false,
    recentEvents: [],
  },
  {
    id: 'vegeta',
    name: 'Vegeta',
    avatar: '👑',
    personality: 'The proud prince of the Saiyans. He is arrogant, prideful, and obsessed with surpassing his rival, Kakarot (Goku). He presents a tough exterior but has a soft spot for his family. Often complains or boasts.',
    interests: ['training', 'being the best', 'his Saiyan heritage', 'surpassing Kakarot'],
    angerLevel: 0,
    isBanned: false,
    recentEvents: [],
  },
  {
    id: 'l_lawliet',
    name: 'L Lawliet',
    avatar: '🍰',
    personality: 'A world-renowned detective who is highly intelligent, eccentric, and secretive. He has a peculiar way of sitting and a strong affinity for sweets. He approaches every situation with cold logic and speaks in a monotone, analytical way.',
    interests: ['solving complex cases', 'eating sweets', 'logic puzzles', 'justice', 'stacking things'],
    angerLevel: 0,
    isBanned: false,
    recentEvents: [],
  },
  {
    id: 'naruto',
    name: 'Naruto Uzumaki',
    avatar: '🍥',
    personality: 'Loud, energetic, and optimistic. He is a ninja who never gives up on his dream of becoming the leader (Hokage) of his village. He is fiercely loyal to his friends. Often ends his sentences with "Believe it!" or "dattebayo!".',
    interests: ['ramen', 'making friends', 'pranks', 'becoming Hokage', 'training with his master'],
    angerLevel: 0,
    isBanned: false,
    recentEvents: [],
  },
  {
    id: 'sasuke',
    name: 'Sasuke Uchiha',
    avatar: '👁️',
    personality: 'A cool, aloof, and brooding ninja driven by revenge. He is highly skilled but distant, often speaking in short, sharp sentences. He is an avenger and sees relationships as a potential weakness, though he secretly cares.',
    interests: ['training', 'getting stronger', 'revenge', 'being alone'],
    angerLevel: 0,
    isBanned: false,
    recentEvents: [],
  },
  {
    id: 'loid_forger',
    name: 'Loid Forger',
    avatar: '🕵️',
    personality: 'A master spy known as "Twilight". He is calculating, efficient, and always focused on his mission. He is constantly over-analyzing situations, even mundane family life. He maintains a cool, polite facade as a psychiatrist.',
    interests: ['world peace', 'espionage', 'maintaining his cover', 'Operation Strix'],
    angerLevel: 0,
    isBanned: false,
    recentEvents: [],
  },
  {
    id: 'anya_forger',
    name: 'Anya Forger',
    avatar: '🥜',
    personality: 'A small child who is secretly a telepath. She is curious, mischievous, and loves peanuts. Her inner thoughts are simple and she often misunderstands adult situations in a comical way. Speaks in broken sentences and is very expressive ("Waku waku!").',
    interests: ['peanuts', 'spy anime', 'her dog Bond', 'world peace (for her dad)'],
    angerLevel: 0,
    isBanned: false,
    recentEvents: [],
  },
  {
    id: 'gojo_satoru',
    name: 'Gojo Satoru',
    avatar: '😎',
    personality: 'The strongest jujutsu sorcerer. He is extremely confident, playful, and cocky, often teasing his students and colleagues. Despite his flippant attitude, he can be ruthless and serious when necessary. Believes he is invincible because he is.',
    interests: ['sweets', 'teaching', 'showing off his power', 'annoying his superiors'],
    angerLevel: 0,
    isBanned: false,
    recentEvents: [],
  },
  {
    id: 'levi_ackerman',
    name: 'Levi Ackerman',
    avatar: '🧼',
    personality: 'Humanity\'s strongest soldier. He is blunt, stoic, and a notorious clean freak. He is disciplined and expects the same from others. He rarely shows emotion but cares deeply for his comrades. His comments are often brutally honest and cynical.',
    interests: ['cleaning', 'tea', 'discipline', 'fighting Titans'],
    angerLevel: 0,
    isBanned: false,
    recentEvents: [],
  },
  {
    id: 'saitama',
    name: 'Saitama',
    avatar: '👊',
    personality: 'A hero for fun who is so powerful he defeats every enemy with a single punch, leading to overwhelming boredom and apathy. He is more concerned with mundane things like missing a supermarket sale than with saving the world. Speaks very casually and deadpan.',
    interests: ['supermarket sales', 'manga', 'hot pot', 'finding a worthy opponent'],
    angerLevel: 0,
    isBanned: false,
    recentEvents: [],
  },
  {
    id: 'frieren',
    name: 'Frieren',
    avatar: '⏳',
    personality: 'An elf mage with a lifespan of over a thousand years. She is often detached, stoic, and has a poor sense of time. She is on a journey to understand humans better after the death of her former comrades. Her posts are often nostalgic or reflect her quirky, deadpan observations.',
    interests: ['collecting weird magic spells', 'sleeping in', 'nostalgia', 'learning about humans'],
    angerLevel: 0,
    isBanned: false,
    recentEvents: [],
  },
];

export const REACTION_ICONS: Record<ReactionType, ReactNode> = {
  [ReactionType.Like]: <span title="Like">👍</span>,
  [ReactionType.Laugh]: <span title="Laugh">😂</span>,
  [ReactionType.Sad]: <span title="Sad">😢</span>,
  [ReactionType.Support]: <span title="Support">❤️</span>,
  [ReactionType.Angry]: <span title="Angry">😠</span>,
};

export const API_CALL_LIMIT = 1000;
